# Generated by Django 4.2.1 on 2023-06-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
