# Generated by Django 4.2.1 on 2023-06-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telovendo', '0002_consultaproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('permiso_clientes', 'Permisos necesarios para clientes'), ('permiso_trabajadores', 'Permisos necesarios para trabajadores'), ('premiso_proveedores', 'Permisos necesarios para proveedores')),
            },
        ),
    ]
